### ISSUE TITLE
Login view disrupted

### ISSUE THREAD

**Issue by tanmayc07** [tanmayc07/Blog-App#12]
![login](https://user-images.githubusercontent.com/48885301/92553872-b9cacc80-f281-11ea-8b2a-091c9423f2bb.png)

# Problem
1. The placeholder of password input seems to be out of its place. 
2. The create account link is not connected to its view. 

# How to reproduce
Enter the address `localhost:5000/auth/login`

# Fixes
1. Check the password input attribute `placeholder`
2. Add a connection to register view in `href` of the respective `a` tag for the create account link.

**Comment by sahilambre** [comment]
@rutu create a PR

**Comment by sahilambre** [comment]
@rutu363 create a PR
