### ISSUE TITLE
Improving Validations

### ISSUE THREAD

**Issue by rutu363** [tanmayc07/Blog-App#15]
**Cannot merge unless all points are working **
[Latest commit](e3a51a5dd29ae539d30166fd5ad5f52947f26eb8) 
Working
1. Minimum length of password is set 6 if password is below 6 it shows the error on the page & wont save in db.

Stopped Working
2.Cannot redirect to login page after correct registeration
3.Sometimes accepts same email multiple times
 ##

**Comment by tanmayc07** [comment]
Can you add the permalink of the commit here? Let me have a look

**Comment by rutu363** [comment]
[Parma link](13b2b5cb00119f76ac8399fa58d2edb7c7880eac)

**Comment by tanmayc07** [comment]
You have defined email as unique. I think the database should reject the email then. [link](https://github.com/tanmayc07/Blog-App/blob/e3a51a5dd29ae539d30166fd5ad5f52947f26eb8/models/User.js#L15)
