### ISSUE TITLE
Redirect issue on login page

### ISSUE THREAD

**Issue by tanmayc07** [tanmayc07/Blog-App#37]
# Problem
![image](https://user-images.githubusercontent.com/48885301/96374954-8ee26b00-1193-11eb-9dcd-8c71afc887cf.png)

The create account link redirects to another `port(3000)` instead of `/auth/register` on the same port(5000) as shown below

![image](https://user-images.githubusercontent.com/48885301/96374979-c6e9ae00-1193-11eb-881c-fe1b5059cc2f.png)

# Solution

The `href` attribute on the button must be changed.

**Comment by tanmayc07** [comment]
Did you test the changes?
Check if it works in `tanmaydev` branch

**Comment by sahilambre** [comment]
Close this issue?

**Comment by tanmayc07** [comment]
Yeah if you tested it, then you can close the issue.
