### ISSUE TITLE
Update explore page UI

### ISSUE THREAD

**Issue by tanmayc07** [tanmayc07/Blog-App#42]
Add username to the blog cards.

![image](https://user-images.githubusercontent.com/48885301/96552798-e981e100-12d1-11eb-8e9c-0875c3a6c5c8.png)
The username can be rendered below the title or in the footer of the card.

**Comment by sahilambre** [comment]
Okay. got it

**Comment by sahilambre** [comment]
I was thinking to remove _View blog_ and _Create Blog_ and instead of that add username. @tanmayc07

**Comment by tanmayc07** [comment]
Yeah that might be okay for now!

**Comment by tanmayc07** [comment]
Closing this issue!
