### ISSUE TITLE
Adding appropriate text to landing page

### ISSUE THREAD

**Issue by sahilambre** [tanmayc07/Blog-App#43]
![image](https://user-images.githubusercontent.com/59484827/96682602-ad648400-1396-11eb-9341-ec44e7b51c97.png)
![image](https://user-images.githubusercontent.com/59484827/96683163-6a56e080-1397-11eb-9200-1683c2f345f8.png)
Will need help to fill the text in here

**Comment by sahilambre** [comment]
**_Can add you suggestions [here](https://docs.google.com/document/d/1UUXmqlj0vpttMdAftWQUR0XhssQekOGeUE__b7nX_Nk/edit) ._**

**Comment by tanmayc07** [comment]
Do you need more help here or is it done?
