### ISSUE TITLE
Backend for My blogs

### ISSUE THREAD

**Issue by tanmayc07** [tanmayc07/Blog-App#45]
Create a function that will return all the blogs of the logged in user from backend to be rendered on my blogs view in frontend.

**Comment by tanmayc07** [comment]
@rutu363 Would you like to work on this?

**Comment by rutu363** [comment]
Solved this issue with [This Commit](https://github.com/tanmayc07/Blog-App/commit/58bb70eab350036d9e53177dbd452d3bcdc4ab8f)

Changes in this commit
1. Created a myblogs view showing only the blogs written by current user
2. Added a listmine function to get data exclusively by the user
![bb](https://user-images.githubusercontent.com/62687761/96905181-bef07d80-14b5-11eb-9e99-69107fa2349d.PNG)
![aa](https://user-images.githubusercontent.com/62687761/96905189-c3b53180-14b5-11eb-92e5-9a49ac6be029.PNG)
3. Added its routes 

//Making a PR

**Comment by tanmayc07** [comment]
@rutu363 Can we close this issue?

**Comment by rutu363** [comment]
Sure lets close it
